version: '3.8'

services:
  backend-yala:
    build: .
    container_name: yala-api
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
    # Esto asegura que los logs no saturen el disco duro del servidor con el tiempo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"